CREATE TABLE IF NOT EXISTS `Person` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Adresse` INTEGER NOT NULL,
	`Name` VARCHAR(255) NOT NULL,
	`Geburtsdatum` DATE NOT NULL,
	`Titel` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Unternehmen` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Adresse` INTEGER NOT NULL,
	`Umsatz` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Protokoll` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Datum` DATETIME NOT NULL,
	`Text` TEXT(65535) NOT NULL,
	`Dauer` INTEGER NOT NULL,
	`TLDR` VARCHAR(255) NOT NULL,
	`Termin` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Termine` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Ort` VARCHAR(255) NOT NULL,
	`Art` INTEGER NOT NULL,
	`Start` DATETIME NOT NULL,
	`Ende` DATETIME NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Terminart` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Adresse` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Plz` INTEGER NOT NULL,
	`ortsname` VARCHAR(255) NOT NULL,
	`Strasse` VARCHAR(255) NOT NULL,
	`Hausnr` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Teilnehmer` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Kontakt` INTEGER NOT NULL,
	`Termin` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Medium` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Dateityp` VARCHAR(255) NOT NULL,
	`Dateiname` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Anhang` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Protokoll` INTEGER NOT NULL,
	`Medium` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Produkt` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Bezeichnung` VARCHAR(255) NOT NULL,
	`Preis` NUMERIC NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Auftrag` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Bezeichnung` VARCHAR(255) NOT NULL,
	`wichtigkeit` INTEGER NOT NULL,
	`Kontakt` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Auftragsposition` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Auftrag` INTEGER NOT NULL,
	`Produkt` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Wichtigkeit` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`level` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Kontakt` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`E-Mail` VARCHAR(255) NOT NULL,
	`Telefonnummer` VARCHAR(255) NOT NULL,
	`Rolle` VARCHAR(255) NOT NULL,
	`Referenz` INTEGER NOT NULL,
	`RefTyp` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Teilnehmer`
ADD FOREIGN KEY(`Kontakt`) REFERENCES `Kontakt`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Termine`
ADD FOREIGN KEY(`Art`) REFERENCES `Terminart`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Teilnehmer`
ADD FOREIGN KEY(`Termin`) REFERENCES `Termine`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Protokoll`
ADD FOREIGN KEY(`Termin`) REFERENCES `Termine`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Anhang`
ADD FOREIGN KEY(`Protokoll`) REFERENCES `Protokoll`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Anhang`
ADD FOREIGN KEY(`Medium`) REFERENCES `Medium`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Person`
ADD FOREIGN KEY(`Adresse`) REFERENCES `Adresse`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Unternehmen`
ADD FOREIGN KEY(`Adresse`) REFERENCES `Adresse`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Kontakt`
ADD FOREIGN KEY(`Referenz`) REFERENCES `Unternehmen`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Kontakt`
ADD FOREIGN KEY(`Referenz`) REFERENCES `Person`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Auftrag`
ADD FOREIGN KEY(`Kontakt`) REFERENCES `Kontakt`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Auftrag`
ADD FOREIGN KEY(`wichtigkeit`) REFERENCES `Wichtigkeit`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Auftragsposition`
ADD FOREIGN KEY(`Auftrag`) REFERENCES `Auftrag`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Auftragsposition`
ADD FOREIGN KEY(`Produkt`) REFERENCES `Produkt`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;